name: Release
on:
  push:
    tags:
      - "*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.18.x'

      - name: Build Linux
        env:
          GOOS: linux
          GOARCH: amd64
        run: |
          go build -o kubot-${{  github.ref_name }}-linux-amd64 kubot.go

      - name: Build MacOS
        env:
          GOOS: darwin
          GOARCH: amd64
        run: |
          go build -o kubot-${{  github.ref_name }}-darwin-amd64 kubot.go

      - name: Build Windows
        env:
          GOOS: windows
          GOARCH: amd64
        run: |
          go build -o kubot-${{  github.ref_name }}-win-amd64.exe kubot.go

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          # note you'll typically need to create a personal access token
          # with permissions to create releases in the other repo
          files: kubot-*
          token: ${{ secrets.GITHUB_TOKEN }}
